[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Xms512M -Xmx1G -XX:+UseG1GC -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/*.jar"
