spring.profiles.default=${ENV:dev}
server.port=${PORT:9191}
management.health.redis.enabled=false

server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript,application/json

server.tomcat.threads.max=200
server.tomcat.max-connections=5000




