spring.datasource.url=${DATABASE_URL:jdbc:mysql://mysql.railway.internal:3306/railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:reUBFtFlctkZqKBXiAMzjeQutThwUxRg}

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

admin.username=${ADMIN_USERNAME:himanshu1997}
admin.password=${ADMIN_PASSWORD:External@12345}

logging.level.root=INFO

jdoodle.client-id=72c792607d19c63ec9f2c27caafe0189
jdoodle.client-secret=a92a78c5314e1b0632ae288580598317b24c0cab57e38f6ed88b5062018115de

spring.data.redis.host=${REDIS_HOST:redis.railway.internal}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:cKwOnfsXulhnHUcZzRqiJMzNHvBtUNyS}
